// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADshbLkQrCrSzUJ2HlCRF1FEhUG4fzdmM',
    appId: '1:316288822813:web:5a52f36ad7d0094587e0f4',
    messagingSenderId: '316288822813',
    projectId: 'bejoy-8c0f2',
    authDomain: 'bejoy-8c0f2.firebaseapp.com',
    storageBucket: 'bejoy-8c0f2.appspot.com',
    measurementId: 'G-BELVZX55Y5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWakfsXvqGOyulbgzbOSvhYsM9v7LPTVs',
    appId: '1:316288822813:ios:aa90225a366134b887e0f4',
    messagingSenderId: '316288822813',
    projectId: 'bejoy-8c0f2',
    storageBucket: 'bejoy-8c0f2.appspot.com',
    iosBundleId: 'com.example.bejoy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWakfsXvqGOyulbgzbOSvhYsM9v7LPTVs',
    appId: '1:316288822813:ios:aa90225a366134b887e0f4',
    messagingSenderId: '316288822813',
    projectId: 'bejoy-8c0f2',
    storageBucket: 'bejoy-8c0f2.appspot.com',
    iosBundleId: 'com.example.bejoy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADshbLkQrCrSzUJ2HlCRF1FEhUG4fzdmM',
    appId: '1:316288822813:web:b3944c8d3b50f90a87e0f4',
    messagingSenderId: '316288822813',
    projectId: 'bejoy-8c0f2',
    authDomain: 'bejoy-8c0f2.firebaseapp.com',
    storageBucket: 'bejoy-8c0f2.appspot.com',
    measurementId: 'G-YFHD3JT1JV',
  );

}